---
title: "linear regression"
author: "Dick boy"
date: "2024-06-11"
output: word_document
---
1.starbucks

```{r}
library(openintro)
```
(1)describe starbucks
```{r}
library(psych)
describe(starbucks)
```
(2)Draw geom_point 

```{r}
library(ggplot2)
ggplot(starbucks, aes(x = carb, y = calories)) +
  geom_point(color = 'blue', shape = 16, size = 3) +
  geom_smooth(method = 'lm', color = 'red') +
  ggtitle("Calories with carb") +
  xlab("carb") +
  ylab("calories") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12)
  )

```
(3)linear regression for starbucks
```{r}
model <- lm(calories ~ carb, data = starbucks)
summary(model)

```

  count confint
```{r}
confint(model,level = 0.95)
```
  analysis of Variance table
```{r}
anova(model)
```


```{r}
coefficients <- coef(model)
intercept <- coefficients[1]
slope <- coefficients[2]

cat("Intercept :", intercept, "\n")
cat("Slope :", slope, "\n")

```
模型的判定系数R²
```{r}
r_squared <- summary(model)$r.squared
r_squared
```
检验一元线性回归的假定
残差图
```{r}
plot(model$residuals)
```
 正态性检验
```{r}
qqnorm(model$residuals)
qqline(model$residuals)
```
 方差齐性检验
```{r}
plot(model$fitted.values, model$residuals)
```
 多元线性回归
1. 描述性分析
使用描述统计相关函数对NELS2数据集进行描述性分析。
```{r}
nels2 <- read.csv("D:\\mycodelife\\workshop\\course_task\\NELS2.csv")
library(psych)
describe(nels2)
```
2. 创建散点图
创建学生成绩（Y轴）与三个自变量（X轴）的散点图
```{r}
pairs(~GRAD + HWIN + HWOUT + BYPARED, data = nels2)
```
3. 相关性分析
```{r}
cor(nels2[, c("GRAD", "HWIN", "HWOUT", "BYPARED")])
```
4. 线性模型拟合
```{r}
model_multi <- lm(GRAD ~ HWIN + HWOUT + BYPARED, data = nels2)

summary(model_multi)
```
5. 模型的判定系数R²及调整后的R²
```{r}
r_squared_multi <- summary(model_multi)$r.squared
r_squared_multi

```

```{r}
adj_r_squared_multi <- summary(model_multi)$adj.r.squared
adj_r_squared_multi
```
6. 检验多元回归的假定
残差图
```{r}
plot(model_multi$residuals)
```
正态性检验
```{r}
qqnorm(model_multi$residuals)
qqline(model_multi$residuals)
```
方差齐性检验
```{r}
plot(model_multi$fitted.values, model_multi$residuals)
```
7. 检验多重共线性
```{r}
library(car)
vif(model_multi)
```

8. 结果整理成规范的表格
```{r}
library(stargazer)
stargazer(model_multi, type = "text")
```
9. 计算置信区间和预测区间

```{r}
confint(model_multi)
# 预测区间
predict(model_multi, interval = "prediction")
```

